# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - linux-notsitecontainers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: docker.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_C37478E8A3E94F738B8FE08259FEBBAE }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_E836E5A04FB740FC8344D6360F7EEF7C }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_C37478E8A3E94F738B8FE08259FEBBAE }}/hello-world:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FD27B0D1FD841F593E0BBDAB15E5EE0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B0FBA683D29F436C9A5B00152E1948A3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_39F4E86B81D34CB1ABAB3569D972F977 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'linux-notsitecontainers'
          slot-name: 'Production'
          images: 'docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_C37478E8A3E94F738B8FE08259FEBBAE }}/hello-world:${{ github.sha }}'
          